### ISSUE TITLE
Port 5010 connection refuesd

### ISSUE THREAD

**Issue by celevra** [BoxSo/ALARMiator-Documentation#2]
Hi,

danke für eure Arbeit!
ich habe frisch einen Server aufgesetzt auf Docker Basis und davor einen Nginx.
Beim erzeugen der QR Codes für die User wird die URL mit http:// und Port 5010 angegeben.
5010 müsste der API Port, ein händisches abändern auf https:// und /api anstatt 5010 bringt leider keinen Erfolg.
Die Frage ist auch weshalb der Server diese URL ausgibt bzw wo man richtig umstellen kann?
Aber selbst wenn ich im Container den Port teste bekomme ich ein connection refused:

```
root@fa45c9350cdc:/alarmiatorserver# curl http://localhost:5010/health/status
curl: (7) Failed to connect to localhost port 5010: Connection refused
```

könnt ihr mich in die richtige Richtung weisen?

Grüße

**Comment by celevra** [comment]
man muss natürlich unter plugins die rest-api erst aktivieren und entsprechen konfigurieren.

**Comment by BoxSo** [comment]
Hi celevra, 

dieses Repo ist nur noch aus Legacy-Gründen offen. Wir haben vor längerer Zeit eine extra Community gestartet, in der User / Admins und Entwickler alle miteinander kommunizieren können. Die findest Du unter https://community.alarmiator.de

Grüße
